require('dotenv').config();
const path = require('path');
const express = require('express');
const cors = require('cors');
const mysql = require('mysql2/promise');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

const app = express();
const port = Number(process.env.PORT || 3000);
const jwtSecret = process.env.JWT_SECRET || 'lionking-development-secret';
const pool = mysql.createPool({ host: process.env.DB_HOST || '127.0.0.1', port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER || 'root', password: process.env.DB_PASSWORD, database: process.env.DB_NAME || 'lionking', waitForConnections: true, connectionLimit: 10 });
app.use(cors()); app.use(express.json()); app.use(express.static(path.join(__dirname)));
function authenticate(request, response, next) { const token = request.headers.authorization?.replace('Bearer ', ''); if (!token) return response.status(401).json({ error: 'Faça login para continuar.' }); try { request.user = jwt.verify(token, jwtSecret); next(); } catch { response.status(401).json({ error: 'Sessão expirada. Faça login novamente.' }); } }
app.get('/api/health', async (_request, response) => { try { await pool.query('SELECT 1'); response.json({ ok: true, database: 'connected' }); } catch { response.status(503).json({ ok: false, database: 'unavailable' }); } });
app.post('/api/auth/register', async (request, response) => { const { name, email, password } = request.body; if (!name || !email || !password || password.length < 6) return response.status(400).json({ error: 'Informe nome, e-mail e senha com pelo menos 6 caracteres.' }); try { const passwordHash = await bcrypt.hash(password, 12); const [result] = await pool.query('INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)', [name.trim(), email.trim().toLowerCase(), passwordHash]); response.status(201).json({ id: result.insertId, name: name.trim(), email: email.trim().toLowerCase() }); } catch (error) { response.status(error.code === 'ER_DUP_ENTRY' ? 409 : 500).json({ error: error.code === 'ER_DUP_ENTRY' ? 'Este e-mail já está cadastrado.' : 'Não foi possível criar a conta.' }); } });
app.post('/api/auth/login', async (request, response) => { const { email, password } = request.body; try { const [rows] = await pool.query('SELECT id, name, email, password_hash FROM users WHERE email = ?', [email.trim().toLowerCase()]); if (!rows[0] || !(await bcrypt.compare(password, rows[0].password_hash))) return response.status(401).json({ error: 'E-mail ou senha inválidos.' }); const user = { id: rows[0].id, name: rows[0].name, email: rows[0].email }; response.json({ user, token: jwt.sign(user, jwtSecret, { expiresIn: '7d' }) }); } catch { response.status(500).json({ error: 'Não foi possível realizar o login.' }); } });
app.get('/api/vehicles', async (request, response) => { try { const filters = []; const values = []; for (const field of ['category', 'type', 'fuel', 'transmission']) if (request.query[field]) { filters.push(`${field} = ?`); values.push(request.query[field]); } if (request.query.search) { filters.push('name LIKE ?'); values.push(`%${request.query.search}%`); } if (request.query.maxPrice) { filters.push('price <= ?'); values.push(Number(request.query.maxPrice)); } const [vehicles] = await pool.query(`SELECT * FROM vehicles ${filters.length ? `WHERE ${filters.join(' AND ')}` : ''} ORDER BY created_at DESC`, values); response.json(vehicles); } catch { response.status(500).json({ error: 'Não foi possível carregar os veículos.' }); } });
app.post('/api/vehicles', authenticate, async (request, response) => { const { name, year, type, category, km, price, image, tag, fuel, transmission, power } = request.body; if (!name || !year || !type || !category || km === undefined || price === undefined) return response.status(400).json({ error: 'Preencha os campos obrigatórios.' }); try { const [result] = await pool.query('INSERT INTO vehicles (name, year, type, category, km, price, image, tag, fuel, transmission, power) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [name, year, type, category, km, price, image || null, tag || 'NOVO ESTOQUE', fuel || null, transmission || null, power || null]); const [rows] = await pool.query('SELECT * FROM vehicles WHERE id = ?', [result.insertId]); response.status(201).json(rows[0]); } catch { response.status(500).json({ error: 'Não foi possível cadastrar o veículo.' }); } });
app.put('/api/vehicles/:id', authenticate, async (request, response) => { try { const fields = ['name', 'year', 'type', 'category', 'km', 'price', 'image', 'tag', 'fuel', 'transmission', 'power'].filter(field => request.body[field] !== undefined); if (!fields.length) return response.status(400).json({ error: 'Nenhum campo enviado.' }); await pool.query(`UPDATE vehicles SET ${fields.map(field => `${field} = ?`).join(', ')} WHERE id = ?`, [...fields.map(field => request.body[field]), request.params.id]); response.json({ ok: true }); } catch { response.status(500).json({ error: 'Não foi possível atualizar o veículo.' }); } });
app.delete('/api/vehicles/:id', authenticate, async (request, response) => { try { await pool.query('DELETE FROM vehicles WHERE id = ?', [request.params.id]); response.status(204).end(); } catch { response.status(500).json({ error: 'Não foi possível excluir o veículo.' }); } });
app.post('/api/favorites/:vehicleId', authenticate, async (request, response) => { try { await pool.query('INSERT IGNORE INTO favorites (user_id, vehicle_id) VALUES (?, ?)', [request.user.id, request.params.vehicleId]); response.status(201).json({ ok: true }); } catch { response.status(500).json({ error: 'Não foi possível salvar o favorito.' }); } });
app.delete('/api/favorites/:vehicleId', authenticate, async (request, response) => { try { await pool.query('DELETE FROM favorites WHERE user_id = ? AND vehicle_id = ?', [request.user.id, request.params.vehicleId]); response.status(204).end(); } catch { response.status(500).json({ error: 'Não foi possível remover o favorito.' }); } });
app.get('/api/favorites', authenticate, async (request, response) => { try { const [rows] = await pool.query('SELECT vehicle_id FROM favorites WHERE user_id = ?', [request.user.id]); response.json(rows.map(row => row.vehicle_id)); } catch { response.status(500).json({ error: 'Não foi possível carregar os favoritos.' }); } });
app.post('/api/interests', async (request, response) => { const { vehicleId, name, email, phone, type } = request.body; if (!vehicleId || !name || !email) return response.status(400).json({ error: 'Informe veículo, nome e e-mail.' }); try { await pool.query('INSERT INTO interests (vehicle_id, name, email, phone, type) VALUES (?, ?, ?, ?, ?)', [vehicleId, name, email, phone || null, type || 'interesse']); response.status(201).json({ ok: true }); } catch { response.status(500).json({ error: 'Não foi possível registrar o interesse.' }); } });
app.listen(port, () => console.log(`Lion King Motors em http://localhost:${port}`));
